version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    network_mode: host

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    network_mode: host